### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by punilnimmagadda** [alap2607/Scrumster#5]
## Description
As a developer, I want to create a nav bar that is configurable to an extent that it should read a JSON to configure the nav bar. 

- Logo should be displayed (Desktop & Mobile - Width: auto, Height: 64px)
- If the nav item has to be displayed as a dropdown, then it should read the children object in the nav JSON object. The nav item should be configurable as a link or a button.
- Maximum width of nav bar should not exceed 2000px.

#### Example JSON:
```
{
  "logoSrc": "/assets/svg/scrumster-logo-color-on-transparent.svg",
  "logoHref": "/",
  "navItems": [
    {
      "displayName": "Home",
      "type": "link",
      "id": "navItemHome",
      "url": "/"
    },
    {
      "displayName": "Tools",
      "type": "link-dropdown",
      "id": "navItemTools",
      "children": [
        {
          "displayName": "Scrum Poker",
          "type": "link",
          "id": "navItemToolsScrumPoker",
          "url": "/scrum-poker",
          "target": "_blank"
        },
        {
          "displayName": "Retro Board",
          "type": "link",
          "id": "navItemToolsRetroBoard",
          "url": "/retro-board",
          "target": "_blank"
        }
      ]
    }
  ]
}
```

## Acceptance Criteria

- Logo should be displayed (autox64)
- Nav items should be configurable
- Nav items should be displayed
- Nav item children should get displayed (if any)
- Maximum width of nav bar should not exceed 2000px.

## Attachments:
**Logo Assets:** [Scrumster Assets.zip](https://github.com/alap2607/Scrumster/files/12923427/Scrumster.Assets.zip)

**Navbar Mock:** 

![Navbar](https://github.com/alap2607/Scrumster/assets/30356661/6eafd6df-3f11-4951-9d88-936d060b7a50)

**Comment by alap2607** [comment]
https://github.com/alap2607/Scrumster/pull/9

<img width="1440" alt="Screenshot 2023-11-21 at 1 44 56 PM" src="https://github.com/alap2607/Scrumster/assets/89713499/92c409c9-8ae9-415e-a2b1-fc746ca065b2">
